### ISSUE TITLE
Supercard DSTwo Plus won't work with Luma 6.1 and 6.1.1

### ISSUE THREAD

**Issue by noX1609** [AuroraWright/Luma3DS#186] opened 2016-08-29 20:28 UTC
Hi,

yesterday i updated from 6.0.1 to 6.1.1 and since this update my Supercard DSTwo Plus doesn't work anymore. When i start it, there is only a Blackscreen and the New 3DS XL freezes.

I then put back Version 6.0.1 and the card is working again.

So please fix that because in 6.0.1 there is often not the right NAND displayed, this is fixed in 6.1.1 but as i said before the Card doesn't work with this version so i cant use it.

Would be happy to see an Update as soon as possible :)

**Comment by cheatfreak47** [comment] 2016-08-29 20:35
My SuperCard DSTwo works fine and you also should check closed issues before making a new one. This is essentially a dupe of #170

**Closed** 2016-08-29 20:51 UTC
